tasks:
  - init: |
      mvn install -P quick-build
    command: mvn hpi:run
  - init: |
      sudo apt update
      sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
      curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
      sudo apt update
      sudo apt install caddy
    command: caddy reverse-proxy --from :5000 --to localhost:8080 -insecure
  - command: gp await-port 8080 && gp url 5000 && gp preview $(gp url 5000)/jenkins/

github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true

jetbrains:
  intellij:
    plugins:
      - Stapler plugin for IntelliJ IDEA
